repository.json
zigbee2mqtt/config.json

Updates based on errors tested with remote repo

---

README.md
zigbee2mqtt/config.json

Adjusted defaults and documentation

---

README.md

Addresses https://github.com/danielwelch/hassio-zigbee2mqtt/issues/24

Updated documentation to use timed permit_join

---

README.md
zigbee2mqtt-edge/config.json
zigbee2mqtt/config.json
zigbee2mqtt/set_config.py

This was implemented in: https://github.com/Koenkk/zigbee2mqtt/issues/133

Added the disable LED of CC2531 to config

---

README.md

the 'set to true' was never updated

Update of log_level in readme

---

zigbee2mqtt-edge/config.json
zigbee2mqtt/test_config.py

* Adds temperature_precision/humidity_precision/pressure_precision to edge config
* Adds new `report` option to edge config

Add missing device specific options to edge

---

zigbee2mqtt-edge/Dockerfile

Remove build dependencies within the same layer as they are installed.
Reduces image size from ~430MB down to ~260MB.

Reduce image size

---

zigbee2mqtt-edge/config.json

@danielwelch  you can merge this to test

Update settings for edge

---

zigbee2mqtt-edge/config.json
zigbee2mqtt/config.json

@danielwelch I have tested the settings with edge and it work fine to more than 12 hours

Update settings, add default network key.

---

README.md
zigbee2mqtt/config.json

Updated broker URL

---

zigbee2mqtt-edge/run.sh
zigbee2mqtt/run.sh

Change from shepard to herdsmen for devices.js

Fix to herdsmen for cutsom devices.js

---

zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

Release version 1.8.0, @Koenkk , @danielwelch  please merge this

Release version 1.8.0

---

CHANGELOG.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

-  ~~[ ] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.~~

Update to 1.11.0

---

README.md

Remove the hide entity lines from automation yaml. #299

Remove hide entity from readme

---

zigbee2mqtt-edge/config.json

See https://github.com/Koenkk/zigbee2mqtt/issues/2253

Add support of experimental transmit_power feature to zigbee2mqtt-edge

---

CHANGELOG.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

Update to 1.12.0

---

CHANGELOG.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

Update to 1.12.1

---

zigbee2mqtt-edge/README.md
zigbee2mqtt-edge/config.json

- Updated edge name for better sidebar integration
- Updated docs for uninstall / install
- Added details (temporary) on how to enable the experimental frontend

Updated name for Edge and added docs for frontend

---

zigbee2mqtt-edge/README.md
zigbee2mqtt-edge/config.json

Fixes for edge

---

zigbee2mqtt-edge/CHANGELOG.md
zigbee2mqtt/CHANGELOG.md

Updated changelog for consistency, added Edge specific changelog

---

zigbee2mqtt/CHANGELOG.md

Removed dates for readability

---

zigbee2mqtt-edge/config.json

Changes based on https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-699683435

Make frontend non-experimental. 

---

common/run.sh
common/socat.sh

Fixing socat

---

common/run.sh
common/socat.sh

Socat simplifications and fixes

---

zigbee2mqtt-edge/Dockerfile
zigbee2mqtt/Dockerfile

Updated Dockerfile to fix curl used in api calls

---

zigbee2mqtt-edge/CHANGELOG.md

Preparing changelog in Edge

---

common/run.sh
common/socat.sh
repository.json

Reverted socat structure changes for fork

---

common/run.sh
zigbee2mqtt-edge/CHANGELOG.md
zigbee2mqtt-edge/config.json

Implemented MQTT auto discovery

---

common/run.sh

Fixed MQTT protocol problems

---

common/run.sh

Made text more readable when MQTT config is not found

Made text more readable

---

zigbee2mqtt/DOCS.md

Wording fixed, removed edge

---

zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/DOCS.md

Added more specific update documentation

---

zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

Bump stable to 1.16

---

zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json

- [x Change the version number in `zigbee2mqtt/config.json`: `"version": "$NEW_VERSION"`

Bump version to 1.16.1

---

zigbee2mqtt-edge/config.json
zigbee2mqtt-edge/run.sh
zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/DOCS.md
zigbee2mqtt/Dockerfile
zigbee2mqtt/config.json
zigbee2mqtt/run.sh

Bump version to 1.16.2

---

zigbee2mqtt-edge/config.json
zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/config.json

Fixes #482 and 483

---

zigbee2mqtt-edge/config.json
zigbee2mqtt/CHANGELOG.md
zigbee2mqtt/config.json

Updated to 1.16.2.2
