danielwelch/hassio-zigbee2mqtt

README.md
- I've set homeassitant to true as it's a better setup for majority of people. 
- I've moved server (mqtt) to mqtt://homeassitant to reuse the dns shared between containers which makes this a viable setup for the majority. Localhost won't work a default
To be honest I think we're losing functionality by dropping the ability to configure the settings in configuration.yaml from the addon options. The way it was before a user never had to touch ssh / yaml and could configure the addon from the UI completely, now it's no longer possible.
=> Corrected some typos and improved defaults

README.md, zigbee2mqtt/config.json, zigbee2mqtt/run.sh
Addressing #10 
Adds a `debug` option to `config.json`, which enables DEBUG mode for zigbee2mqtt and zigbee-shepherd
=> exposing debug option

zigbee2mqtt/config.json
The [Hass.io dev docs](https://developers.home-assistant.io/docs/en/hassio_addon_config.html) make it seem like the `auto_uart` option will fix our issue with device mapping. It just maps all serial devices from host into add-on.
@ciotlosm this may be the solution to the device mapping issue
=> Fix device mapping

README.md, zigbee2mqtt/Dockerfile, zigbee2mqtt/run.sh
- Added pm2 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/2
- Added documentation for allow on the fly `permit_join` from home assistant https://github.com/danielwelch/hassio-zigbee2mqtt/issues/15
Note: Might be worth changing version to 0.1 after this is tested.
=> Added pm2 and permit_join through interface docs

CHANGELOG.md, README.md, zigbee2mqtt-edge/config.json, zigbee2mqtt/config.json, zigbee2mqtt/run.sh, zigbee2mqtt/set_config.py
Addresses #50 
- remove `debug` and `err` options from hass.io UI, as I think the logging in zigbee2mqtt has improved and this should no longer be necessary.
- refactor how zigbee2mqtt config is built so it's easier to add more options later if needed
Todo:
=> updating options

zigbee2mqtt-edge/Dockerfile, zigbee2mqtt-edge/config.json, zigbee2mqtt-edge/run.sh
- See 82f7b41 for most of the documentation
- Config is parsed as json and not yaml. Because json is a subclass of yaml and
z2m excepts yaml this works well
- makes use of [device and group config](https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/configuration/configuration.md#specifying-devices-and-groups-in-a-separate-file) as it was added to z2m with https://github.com/Koenkk/zigbee2mqtt/commit/516bd704c67b0c86a323e5d90d9149d539fa6e7e
this splits off group and device config from the main config, as it is not trivial to manage user input
and z2m independently manipulating a common config file.
=> Make use of nested configuration **Breaking Change** 

zigbee2mqtt-edge/config.json, zigbee2mqtt/config.json
Hass.io has recently introduced the armv7 architecture.
The add-ons in this repository do not specify the supported architectures, hence it falls back into its default: All architecture. However, armv7 is not available for this add-on, hence people that have a supported armv7 device (e.g., Raspberry Pi 3) will get a 404 not found error on installing this add-on.
This PR fixes it, by explicitly defining the supported architectured in the add-on config. Please note, that an armv7 device, will fallback to armhf automatically. So using this, your add-on will be available on all platforms as usual.
A release of the add-on is not needed for this change.
fixes #123 
@danielwelch You might need to apply the same for the other add-ons. Of course, you can decide to supply armv7 (nice speed boost). …
=> Fixes supported architectures

.travis.yml, build.sh, distribute.sh, zigbee2mqtt-edge/Dockerfile
Pass in travis_commit var to docker build, to create .hash.json during build process. This should be displayed in the log by zigbee2mqtt when ran (see https://github.com/danielwelch/hassio-zigbee2mqtt/issues/146)
=> Create .hash.json during build process

zigbee2mqtt/config.json
There is a copy error in the default config. This changes the default config to use false instead of "bool?" from disable_led.
=> Change "bool?" to false in default config fixes #197

zigbee2mqtt/run.sh
After installation of addon version 1.5.1.1 I got the following error message:
```
./run.sh: line 20: /share/zigbee2mqtt/configuration.yaml: No such file or directory
```
Creating the directory (DATA_PATH) will fix this issue.
=> Fix error "configuration.yaml: No such file"

README.md, zigbee2mqtt/Dockerfile, zigbee2mqtt/README.md, zigbee2mqtt/config.json
(Hopefully) the needed pull request to implement #253. My understanding of the lack of specific upgrade instructions on the `zigbee2mqtt` `1.7.0` release is, that the upgrade should be painless (i.e. automatic). Correct me if I'm wrong.
I also expanded on the "breaking changes" in the `README.md`, adding the specific note for `1.6.0` to `1.7.0` release notes from the [1.7.0 release notes](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.7.0).
=> Upgrade to v1.7.0

CHANGELOG.md, README.md, zigbee2mqtt-edge/config.json, zigbee2mqtt-edge/run.sh, zigbee2mqtt/README.md, zigbee2mqtt/config.json, zigbee2mqtt/run.sh
Support both extended PAN ID and network key *as strings*. That way
* extended PAN ID can be made optional (arrays cannot be made optional in the Hass.io add-on schema, so adding it - being mandatory - would break existing installations)
* the network key can be read from the secrets file (strings can be read from the secrets file whereas arrays can not)
Follow up to https://github.com/danielwelch/hassio-zigbee2mqtt/pull/263 and https://github.com/danielwelch/hassio-zigbee2mqtt/issues/259.
Example configuration:
```javascript
{
// ...
"advanced": {
// ...
"ext_pan_id_string": "1, 2, 3, 4, 5, 6, 7, 8",
// ...
"network_key": [],
"network_key_string": "1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13",
// ...
},
// ...
}
```
Please note that `network_key` still needs to be present in the …
=> Support extended PAN ID (optional) & secret network_key

zigbee2mqtt-edge/config.json
Hello,
Thx for your addon.
I wanted use my own ssl secured connection. But I didn't want copy certificate en several path;
So I change the config.json to mount ssl folder from hass.
It's described in this documentation section "map".
https://developers.home-assistant.io/docs/en/next/hassio_addon_config.html#options--schema
Sincerely,
Turiok
=> mount ssl folder from hass to use certificate

zigbee2mqtt/config.json
See https://github.com/Koenkk/zigbee2mqtt/issues/2253
=> Add support of experimental transmit_power feature to zigbee2mqtt stable.

zigbee2mqtt-edge/config.json, zigbee2mqtt/config.json
Adds the "adapter_concurrent" option. 
https://github.com/Koenkk/zigbee-herdsman/pull/159
https://github.com/Koenkk/zigbee2mqtt/issues/4250
=> adding adapter_concurrent option to config

zigbee2mqtt-edge/config.json, zigbee2mqtt/config.json
Adds support for the advanced setting `homeassistant_legacy_triggers`
Zigbee2mqtt issue: Koenkk/zigbee2mqtt#3033
Fixes #313, #375
=> Add advanced setting homeassistant_legacy_triggers

README.md
Replace Hass.io with Home Assistant. Also, try to match/re-use the wording as close as possible.
=> Rename Hass.io to Home Assistant

zigbee2mqtt-edge/Dockerfile, zigbee2mqtt-edge/config.json, zigbee2mqtt/config.json
=> add explicit armv7 support; fix .hash.json generation

zigbee2mqtt-edge/config.json
Add support for experimental frontend in edge so people can troubleshoot easier. 
Part of testing for https://github.com/danielwelch/hassio-zigbee2mqtt/issues/397
I will not add the settings in `stable` as probably settings will change.
=> Add support for experimental frontend in edge

zigbee2mqtt-edge/config.json, zigbee2mqtt/CHANGELOG.md, zigbee2mqtt/config.json
=> New configuration option advanced/adapter_delay and adapter: zigate, fixes #499, #498
